---
# Configures the consul agents
# Config file at /etc/consul.d/consul.json

# Template:
# datacenter = "dc1"
# data_dir = "/opt/consul"
# encrypt = "qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0="
# verify_incoming = true
# verify_outgoing = true
# verify_server_hostname = true

# TLS Config
# Server:
# ca_file = "<Consul configuration directory>/certs/consul-agent-ca.pem"
# cert_file = "<Consul configuration directory>/certs/dc1-server-consul-0.pem"
# key_file = "<Consul configuration directory>/certs/dc1-server-consul-0-key.pem"
#
# auto_encrypt {
#   allow_tls = true
# }
# Client:
# ca_file = "<Consul configuration directory>/certs/consul-agent-ca.pem"
#
# auto_encrypt {
#   tls = true
# }

# DC auto-join
# retry_join = ["172.16.0.11"]

# Enable ACLs
# acl {
#   enabled = true
#   default_policy = "deny"
#   enable_token_persistence = true
# }

# Performance:
# Not included here, but see https://www.consul.io/docs/install/performance

# Telemetry:
# Not included here, but see https://learn.hashicorp.com/tutorials/consul/monitor-datacenter-health

# - name: Write configuration file
#   template:
#     src: "consul.hcl.j2"
#     dest: /etc/consul.d/consul.hcl
#     owner: "{{ consul_user }}"
#     group: "{{ consul_group }}"
#     mode: 0640
#   notify: restart consul
